/*
 * tigger_rule.java
 *
 * Created on __DATE__, __TIME__
 */

package shuiguoji;

import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author  __USER__
 */
public class tigger_rule extends javax.swing.JFrame {

	/** Creates new form tigger_rule */
	public tigger_rule() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton1.setText("返回游戏");

		jLabel1.setText("水果机规则");

		jLabel2.setText(" 1.游戏介绍：");

		jLabel3.setText("  （1）通过点击摇杆开始游戏；");

		jLabel4.setText("  （2）通过点击幸运一刻暂停水果轮播；");

		jLabel5.setText(" 2.赔率：");

		jLabel6.setText("  （1）假如出现两个相同的水果则获得下注的双倍积分；");

		jLabel7.setText("  （2）假如出现三个相同的水果则获得下注的三倍积分；");

		jLabel8.setText("  （3）假如为出现一样的水果则失去下注积分；");

		jLabel9.setText("祝你游戏愉快");

		jLabel10.setText("");
		
		int windowWidth = this.getWidth(); // 获得窗口宽   
		int windowHeight = this.getHeight(); // 获得窗口高  
		Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包   
		Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸   
		int screenWidth = screenSize.width; // 获取屏幕的宽   
		int screenHeight = screenSize.height; // 获取屏幕的高   
		this.setLocation(screenWidth / 4 - windowWidth / 2, screenHeight /
				4 - windowHeight / 2);// 设置窗口居中显示
		
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
						.addContainerGap(361, Short.MAX_VALUE)).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel4)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel5)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel6)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel7)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel8)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel9)
						.addContainerGap()).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel10)
						.addContainerGap()).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout.createSequentialGroup().addContainerGap(319,
						Short.MAX_VALUE).addComponent(jButton1)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel9)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel10)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).addComponent(
												jButton1)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new tigger().setVisible(true);
		this.setVisible(false);
	}

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new tigger_rule().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}