/*
 * bag.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

import model.User;

import View.menu1.ImagePanel;

/**
 *
 * @author  __USER__
 */
public class bag extends javax.swing.JFrame {
	public User u;

	//	this.jLabel1.setIcon(new ImageIcon("src/img/九.png")); // NOI18N

	/** Creates new form bag */
	public bag(User u) {
		this.u = u;
		String temp;
		initComponents();
		if (!u.getI1().equals("none")) {
			temp = u.getI1();
			this.jLabel1.setIcon(new ImageIcon("src/img/" + temp + ".png")); // NOI18N
		}
		if (!u.getI2().equals("none")) {
			temp = u.getI2();
			this.jLabel3.setIcon(new ImageIcon("src/img/" + temp + ".png"));
		}
		if (!u.getI3().equals("none")) {
			temp = u.getI3();
			this.jLabel4.setIcon(new ImageIcon("src/img/" + temp + ".png"));
		}
		if (!u.getI4().equals("none")) {
			temp = u.getI4();
			this.jLabel10.setIcon(new ImageIcon("src/img/" + temp + ".png"));
		}
		if (!u.getI5().equals("none")) {
			temp = u.getI5();
			this.jLabel7.setIcon(new ImageIcon("src/img/" + temp + ".png"));
		}
		if (!u.getI6().equals("none")) {
			temp = u.getI6();
			this.jLabel6.setIcon(new ImageIcon("src/img/" + temp + ".png"));
		} else {

		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//jPanel1 =new ImagePanel(new ImageIcon("src/img/bagg.jpg").getImage());
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 =new ImagePanel(new ImageIcon("src/img/bagg.jpg").getImage());
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		
		
		int windowWidth = this.getWidth(); 
        int windowHeight = this.getHeight();   
		Toolkit kit = Toolkit.getDefaultToolkit(); // 定义工具包   
		Dimension screenSize = kit.getScreenSize(); // 获取屏幕的尺寸   
		int screenWidth = screenSize.width;  
		int screenHeight = screenSize.height; 
        this.setLocation(screenWidth / 4 - windowWidth / 2, screenHeight / 
              4 - windowHeight / 2);// 设置窗口居中显示
		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/商城.jpg"))); // NOI18N

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/X.jpg"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel1MouseEntered(evt);
			}
		});

		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel3MouseEntered(evt);
			}
		});

		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel4MouseEntered(evt);
			}
		});

		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel6MouseEntered(evt);
			}
		});

		jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel7MouseEntered(evt);
			}
		});

		jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel10MouseEntered(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(179, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				130,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				44,
																				44,
																				44))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel10,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												87,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												87,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												9,
																												9,
																												9)
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												87,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												jButton3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												40,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGroup(
																												jPanel1Layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																84,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jLabel3,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																87,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jLabel4,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																87,
																																javax.swing.GroupLayout.PREFERRED_SIZE))))
																		.addGap(
																				292,
																				292,
																				292)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(45, 45, 45)
										.addComponent(
												jButton3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																83,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																83,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																83,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				83,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				83,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				83,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												95, Short.MAX_VALUE)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												41,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {
		int number0 = u.getInumber6();
		String text = Integer.toString(number0);
		this.jLabel6.setToolTipText(text);
	}

	private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {
		int number0 = u.getInumber5();
		String text = Integer.toString(number0);
		this.jLabel7.setToolTipText(text);
	}

	private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {
		int number0 = u.getInumber4();
		String text = Integer.toString(number0);
		this.jLabel10.setToolTipText(text);
	}

	private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		int number0 = u.getInumber3();
		String text = Integer.toString(number0);
		this.jLabel4.setToolTipText(text);
	}

	private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {
		int number0 = u.getInumber2();
		String text = Integer.toString(number0);
		this.jLabel3.setToolTipText(text);
	}

	private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		int number0 = u.getInumber1();
		String text = Integer.toString(number0);
		this.jLabel1.setToolTipText(text);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new menu1(u).setVisible(true);
		this.setVisible(false);
	}

	@SuppressWarnings("serial")
	public class ImagePanel extends JPanel {
		private Image img;

		public ImagePanel(String img) {
			this(new ImageIcon(img).getImage());
		}

		public ImagePanel(Image img) {
			this.img = img;
			// 定义图像尺寸
			Dimension size = new Dimension(img.getWidth(null), img
					.getHeight(null));
			setPreferredSize(size);
			setMinimumSize(size);
			setMaximumSize(size);
			setSize(size);
			// 定义布局方式为空
			setLayout(null);
			setDoubleBuffered(true);
		}

		public void paintComponent(Graphics g) {
			g.drawImage(img, 0, 0, null);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	//	public static void main(String args[]) {
	//		java.awt.EventQueue.invokeLater(new Runnable() {
	//			public void run() {
	//				new bag().setVisible(true);
	//			}
	//		});
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}